"""ADDS Phase 1 longitudinal vehicle simulator."""

from .batch import BatchEvaluationResult, run_batch_evaluation
from .benchmarks import benchmark_scenarios
from .comparison import PairedComparisonResult, run_paired_comparison
from .controllers import (
    CoastController,
    ConstantEngineTorqueController,
    ConventionalBaselineController,
    OfflineOptimizedADDSController,
    RuleBasedADDSController,
    ScriptedModeController,
    SpeedTrackingController,
    coast_is_feasible,
)
from .defaults import default_simulation_config
from .learned_controller import LearnedADDSController
from .metrics import summarize_run
from .ml import (
    BehavioralCloningModel,
    ImitationExample,
    TrainingReport,
    collect_imitation_examples,
    train_behavioral_cloning_model,
)
from .parameters import (
    CouplingParameters,
    EngineParameters,
    EnvironmentParameters,
    SafetyParameters,
    SolverParameters,
    TransmissionParameters,
    VehicleParameters,
)
from .profiles import ConstantProfile, OffsetProfile, PiecewiseLinearProfile
from .robustness import (
    ParameterPerturbation,
    RobustnessReport,
    RobustnessRun,
    apply_perturbation_to_config,
    apply_perturbation_to_scenario,
    default_perturbations,
    run_robustness_evaluation,
    write_robustness_report,
)
from .scenario_catalog import ScenarioCatalogEntry, entries_by_split, phase4_scenario_catalog
from .simulator import LongitudinalSimulator, Scenario, SimulationConfig, SimulationResult, VehicleState
from .visualization import (
    DashboardCatalogRow,
    DashboardComparison,
    DashboardEvaluationThresholds,
    DashboardInsight,
    DashboardModeDuration,
    DashboardModeTransition,
    DashboardScenarioOption,
    DashboardSensitivityRow,
    DashboardSensitivitySummary,
    DashboardVerdict,
    available_dashboard_scenarios,
    build_dashboard_catalog_summary,
    build_dashboard_comparison,
    build_dashboard_sensitivity,
    evaluate_dashboard_comparison,
    insights_for_dashboard,
    mode_duration_rows,
    metric_cards_for_dashboard,
    mode_durations_seconds,
    mode_transition_rows,
    records_for_dashboard,
)

__all__ = [
    "CoastController",
    "ConstantEngineTorqueController",
    "ConstantProfile",
    "ConventionalBaselineController",
    "CouplingParameters",
    "DashboardCatalogRow",
    "DashboardComparison",
    "DashboardEvaluationThresholds",
    "DashboardInsight",
    "DashboardModeDuration",
    "DashboardModeTransition",
    "DashboardScenarioOption",
    "DashboardSensitivityRow",
    "DashboardSensitivitySummary",
    "DashboardVerdict",
    "BatchEvaluationResult",
    "BehavioralCloningModel",
    "EngineParameters",
    "EnvironmentParameters",
    "ImitationExample",
    "LearnedADDSController",
    "LongitudinalSimulator",
    "OffsetProfile",
    "OfflineOptimizedADDSController",
    "ParameterPerturbation",
    "PiecewiseLinearProfile",
    "PairedComparisonResult",
    "RuleBasedADDSController",
    "RobustnessReport",
    "RobustnessRun",
    "Scenario",
    "ScenarioCatalogEntry",
    "ScriptedModeController",
    "SafetyParameters",
    "SimulationConfig",
    "SimulationResult",
    "SolverParameters",
    "SpeedTrackingController",
    "TrainingReport",
    "TransmissionParameters",
    "VehicleParameters",
    "VehicleState",
    "apply_perturbation_to_config",
    "apply_perturbation_to_scenario",
    "available_dashboard_scenarios",
    "benchmark_scenarios",
    "build_dashboard_catalog_summary",
    "build_dashboard_comparison",
    "build_dashboard_sensitivity",
    "collect_imitation_examples",
    "coast_is_feasible",
    "default_simulation_config",
    "default_perturbations",
    "entries_by_split",
    "evaluate_dashboard_comparison",
    "insights_for_dashboard",
    "metric_cards_for_dashboard",
    "mode_duration_rows",
    "mode_durations_seconds",
    "mode_transition_rows",
    "phase4_scenario_catalog",
    "records_for_dashboard",
    "run_batch_evaluation",
    "run_paired_comparison",
    "run_robustness_evaluation",
    "summarize_run",
    "train_behavioral_cloning_model",
    "write_robustness_report",
]
